config/routes.rb
ShoppingSiteTemplate::Application.routes.draw do
  resources :issue_items

  resources :lucky_todays

  resources :frontpages

  resources :sellers

  resources :product_categories

  resources :products

  resources :users

  resources :sessions

  root 'sessions#new'

  

end

app/models/billing.rb
class Billing < ActiveRecord::Base

  has_many :billing_products
  belongs_to :user

end

app/models/billing_product.rb
class BillingProduct < ActiveRecord::Base

  belongs_to :billing

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :user

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  has_many :products
end

app/models/frontpage.rb
class Frontpage < ActiveRecord::Base

  has_many :products



end

app/models/issue_item.rb
class IssueItem < ActiveRecord::Base

  has_many :products

end

app/models/lucky_today.rb
class LuckyToday < ActiveRecord::Base

  has_many :products


end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_images
  belongs_to :product_category
  belongs_to :seller


end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base

  has_many :products

  # self join association
  has_many :subCategories, class_name: 'ProductCategory', foreign_key: 'superCategory_id'
  belongs_to :superCategory, class_name: 'ProductCategory'


end

app/models/product_comment.rb
class ProductComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base

  belongs_to :product

end

app/models/search_history.rb
class SearchHistory < ActiveRecord::Base



end

app/models/seller.rb
class Seller < ActiveRecord::Base

  has_many :products


end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :user
  has_many :products


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :product_comments
  has_one :shopping_cart
  has_one :favorite
  has_many :coupons

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :userId,  presence: true,
                      length: { within: 6..15 } ,
                      uniqueness: true
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :password, presence: true,
                       confirmation: true,
                       length: { within: 6..50 }
  validates :email, presence: true,
            format: {with: email_regex },
            uniqueness: {case_sensitive: false }
  validates :terms_of_service, acceptance: {accept: '1'}


  def self.authenticate(params)
    puts "IN authenticate params #{params[:userId]}"
    puts "IN authenticate params #{params[:password]}"
    user = User.find_by(userId: params[:userId])
    puts "IN authenticate #{user.to_s}"
    if user && user.password == encrypt_password(params[:password])
      user
    else
      nil
    end
  end

  def self.encrypt_password(password)
    Digest::MD5.hexdigest(password)
  end

end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render action: 'show', status: :created, location: @seller }
      else
        format.html { render action: 'new' }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:name, :tel, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontpages_helper.rb
module FrontpagesHelper
end

app/helpers/issue_items_helper.rb
module IssueItemsHelper
end

app/helpers/lucky_todays_helper.rb
module LuckyTodaysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sellers/edit.html.erb
<h1>Editing seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @seller %> |
<%= link_to 'Back', sellers_path %>

app/views/sellers/index.html.erb
<h1>Listing sellers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tel</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sellers.each do |seller| %>
      <tr>
        <td><%= seller.name %></td>
        <td><%= seller.tel %></td>
        <td><%= seller.address %></td>
        <td><%= link_to 'Show', seller %></td>
        <td><%= link_to 'Edit', edit_seller_path(seller) %></td>
        <td><%= link_to 'Destroy', seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_seller_path %>

app/views/sellers/new.html.erb
<h1>New seller</h1>

<%= render 'form' %>

<%= link_to 'Back', sellers_path %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @seller.name %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @seller.tel %>
</p>

<p>
  <strong>Address:</strong>
  <%= @seller.address %>
</p>

<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>