config/routes.rb
ShoppingSiteTemplate::Application.routes.draw do
  resources :issue_items

  resources :lucky_todays

  resources :frontpages

  resources :sellers

  resources :product_categories

  resources :products

  resources :users

  resources :sessions

  root 'sessions#new'

  

end

app/models/billing.rb
class Billing < ActiveRecord::Base

  has_many :billing_products
  belongs_to :user

end

app/models/billing_product.rb
class BillingProduct < ActiveRecord::Base

  belongs_to :billing

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :user

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  has_many :products
end

app/models/frontpage.rb
class Frontpage < ActiveRecord::Base

  has_many :products



end

app/models/issue_item.rb
class IssueItem < ActiveRecord::Base

  has_many :products

end

app/models/lucky_today.rb
class LuckyToday < ActiveRecord::Base

  has_many :products


end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_images
  belongs_to :product_category
  belongs_to :seller


end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base

  has_many :products

  # self join association
  has_many :subCategories, class_name: 'ProductCategory', foreign_key: 'superCategory_id'
  belongs_to :superCategory, class_name: 'ProductCategory'


end

app/models/product_comment.rb
class ProductComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base

  belongs_to :product

end

app/models/search_history.rb
class SearchHistory < ActiveRecord::Base



end

app/models/seller.rb
class Seller < ActiveRecord::Base

  has_many :products


end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :user
  has_many :products


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :product_comments
  has_one :shopping_cart
  has_one :favorite
  has_many :coupons

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :userId,  presence: true,
                      length: { within: 6..15 } ,
                      uniqueness: true
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :password, presence: true,
                       confirmation: true,
                       length: { within: 6..50 }
  validates :email, presence: true,
            format: {with: email_regex },
            uniqueness: {case_sensitive: false }
  validates :terms_of_service, acceptance: {accept: '1'}


  def self.authenticate(params)
    puts "IN authenticate params #{params[:userId]}"
    puts "IN authenticate params #{params[:password]}"
    user = User.find_by(userId: params[:userId])
    puts "IN authenticate #{user.to_s}"
    if user && user.password == encrypt_password(params[:password])
      user
    else
      nil
    end
  end

  def self.encrypt_password(password)
    Digest::MD5.hexdigest(password)
  end

end

app/controllers/lucky_todays_controller.rb
class LuckyTodaysController < ApplicationController
  before_action :set_lucky_today, only: [:show, :edit, :update, :destroy]

  # GET /lucky_todays
  # GET /lucky_todays.json
  def index
    @lucky_todays = LuckyToday.all
  end

  # GET /lucky_todays/1
  # GET /lucky_todays/1.json
  def show
  end

  # GET /lucky_todays/new
  def new
    @lucky_today = LuckyToday.new
  end

  # GET /lucky_todays/1/edit
  def edit
  end

  # POST /lucky_todays
  # POST /lucky_todays.json
  def create
    @lucky_today = LuckyToday.new(lucky_today_params)

    respond_to do |format|
      if @lucky_today.save
        format.html { redirect_to @lucky_today, notice: 'Lucky today was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lucky_today }
      else
        format.html { render action: 'new' }
        format.json { render json: @lucky_today.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lucky_todays/1
  # PATCH/PUT /lucky_todays/1.json
  def update
    respond_to do |format|
      if @lucky_today.update(lucky_today_params)
        format.html { redirect_to @lucky_today, notice: 'Lucky today was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lucky_today.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lucky_todays/1
  # DELETE /lucky_todays/1.json
  def destroy
    @lucky_today.destroy
    respond_to do |format|
      format.html { redirect_to lucky_todays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lucky_today
      @lucky_today = LuckyToday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lucky_today_params
      params.require(:lucky_today).permit(:applied_at, :discountRate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontpages_helper.rb
module FrontpagesHelper
end

app/helpers/issue_items_helper.rb
module IssueItemsHelper
end

app/helpers/lucky_todays_helper.rb
module LuckyTodaysHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lucky_todays/_form.html.erb
<%= form_for(@lucky_today) do |f| %>
  <% if @lucky_today.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lucky_today.errors.count, "error") %> prohibited this lucky_today from being saved:</h2>

      <ul>
      <% @lucky_today.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :applied_at %><br>
    <%= f.date_select :applied_at %>
  </div>
  <div class="field">
    <%= f.label :discountRate %><br>
    <%= f.number_field :discountRate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lucky_todays/edit.html.erb
<h1>Editing lucky_today</h1>

<%= render 'form' %>

<%= link_to 'Show', @lucky_today %> |
<%= link_to 'Back', lucky_todays_path %>

app/views/lucky_todays/index.html.erb
<h1>Listing lucky_todays</h1>

<table>
  <thead>
    <tr>
      <th>Applied at</th>
      <th>Discountrate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lucky_todays.each do |lucky_today| %>
      <tr>
        <td><%= lucky_today.applied_at %></td>
        <td><%= lucky_today.discountRate %></td>
        <td><%= link_to 'Show', lucky_today %></td>
        <td><%= link_to 'Edit', edit_lucky_today_path(lucky_today) %></td>
        <td><%= link_to 'Destroy', lucky_today, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lucky today', new_lucky_today_path %>

app/views/lucky_todays/new.html.erb
<h1>New lucky_today</h1>

<%= render 'form' %>

<%= link_to 'Back', lucky_todays_path %>

app/views/lucky_todays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applied at:</strong>
  <%= @lucky_today.applied_at %>
</p>

<p>
  <strong>Discountrate:</strong>
  <%= @lucky_today.discountRate %>
</p>

<%= link_to 'Edit', edit_lucky_today_path(@lucky_today) %> |
<%= link_to 'Back', lucky_todays_path %>