config/routes.rb
ShoppingSiteTemplate::Application.routes.draw do
  resources :issue_items

  resources :lucky_todays

  resources :frontpages

  resources :sellers

  resources :product_categories

  resources :products

  resources :users

  resources :sessions

  root 'sessions#new'

  

end

app/models/billing.rb
class Billing < ActiveRecord::Base

  has_many :billing_products
  belongs_to :user

end

app/models/billing_product.rb
class BillingProduct < ActiveRecord::Base

  belongs_to :billing

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :user

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  has_many :products
end

app/models/frontpage.rb
class Frontpage < ActiveRecord::Base

  has_many :products



end

app/models/issue_item.rb
class IssueItem < ActiveRecord::Base

  has_many :products

end

app/models/lucky_today.rb
class LuckyToday < ActiveRecord::Base

  has_many :products


end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_images
  belongs_to :product_category
  belongs_to :seller


end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base

  has_many :products

  # self join association
  has_many :subCategories, class_name: 'ProductCategory', foreign_key: 'superCategory_id'
  belongs_to :superCategory, class_name: 'ProductCategory'


end

app/models/product_comment.rb
class ProductComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base

  belongs_to :product

end

app/models/search_history.rb
class SearchHistory < ActiveRecord::Base



end

app/models/seller.rb
class Seller < ActiveRecord::Base

  has_many :products


end

app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  belongs_to :user
  has_many :products


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :product_comments
  has_one :shopping_cart
  has_one :favorite
  has_many :coupons

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :userId,  presence: true,
                      length: { within: 6..15 } ,
                      uniqueness: true
  validates :firstName, presence: true
  validates :lastName, presence: true
  validates :password, presence: true,
                       confirmation: true,
                       length: { within: 6..50 }
  validates :email, presence: true,
            format: {with: email_regex },
            uniqueness: {case_sensitive: false }
  validates :terms_of_service, acceptance: {accept: '1'}


  def self.authenticate(params)
    puts "IN authenticate params #{params[:userId]}"
    puts "IN authenticate params #{params[:password]}"
    user = User.find_by(userId: params[:userId])
    puts "IN authenticate #{user.to_s}"
    if user && user.password == encrypt_password(params[:password])
      user
    else
      nil
    end
  end

  def self.encrypt_password(password)
    Digest::MD5.hexdigest(password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frontpages_helper.rb
module FrontpagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingSiteTemplate</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
  <%= render "shared/menu" %>
</div>

<%= yield %>

</body>
</html>

app/views/shared/_menu.html.erb
<div id="login_info">
  <% if $user_name %>
    Welcome <%= $user_name %>
  <% end %>
</div>
<div id="navcontainer">
  <ul>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Products', products_path %></li>
    <li><%= link_to 'Category', product_categories_path %></li>
    <li><%= link_to 'Seller', sellers_path %></li>
    <li><%= link_to 'Frontpage setup', frontpages_path %></li>
    <li><%= link_to 'Issue Item ', issue_items_path %></li>
    <li><%= link_to 'Lucky Today', lucky_todays_path %></li>
  </ul>
</div>